### ISSUE TITLE
check_model(x) Error in grid.Call....

### ISSUE THREAD

**Issue by dpmoriarity** [easystats/performance#353]
Hello all, 

Sorry to bother you again without a week's rest from my last issue, but now I am receiving the below error when I try to use check_model for an lm model. I tested other performance functions (e.g., r2(), check_normality()   ), and they seem to work fine. This can be reproduced using the below code:

model <- lm(mpg ~ wt + cyl, data = mtcars)
check_model(model)

check_model(x) Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  :    Viewport has zero dimension(s) In addition: Warning message: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.

**Comment by bwiernik** [comment]
I cannot reproduce that. 

The last warning message suggests that you have an outdated version of *see* installed. Please double check that the error still persists with the latest version:

Restart R, then run:

```r
install.packages('datawizard', repos = 'https://easystats.r-universe.dev')
easystats::install_latest()
```

Then run your code again:
```r
library(performance)
model <- lm(mpg ~ wt + cyl, data = mtcars)
check_model(model)
```

**Comment by dpmoriarity** [comment]
Hi Brenton,

Thanks for your patience and help with this. I am using the most up to date version of R (I'm actually running these analyses remotely from the same desktop that I got the last code to work for, my home laptop always has a hard time with packages that need to be pulled from a diff repo).

I double checked that I'm in the most up to date version of R. I ran your suggested code and it said I had to install 'patchwork'. I did so but, after that, the same error came up: Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  :
  Viewport has zero dimension(s)

My best,
Daniel

Doctoral Student, Clinical Area
Mood and Cognition Lab
Department of Psychology
Temple University

________________________________
From: Brenton M. Wiernik ***@***.***>
Sent: Tuesday, August 17, 2021 6:52 PM
To: easystats/performance ***@***.***>
Cc: Daniel P Moriarity ***@***.***>; Author ***@***.***>
Subject: [External] Re: [easystats/performance] check_model(x) Error in grid.Call.... (#353)


I cannot reproduce that.

The last warning message suggests that you have an outdated version of see installed. Please double check that the error still persists with the latest version:

Restart R, then run:

install.packages('datawizard', repos = 'https://easystats.r-universe.dev')
easystats::install_latest()

Then run your code again:

library(performance)
model <- lm(mpg ~ wt + cyl, data = mtcars)
check_model(model)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Feasystats%2Fperformance%2Fissues%2F353%23issuecomment-900682948&data=04%7C01%7Cmort963%40temple.edu%7C818734b7e125421ec56208d961d1a132%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637648375258379169%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DhKMYC5hq3eRfcfpC2J5Aa8jwmTGtD%2FBDKk3RR%2BBRXM%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJ52722I34ZX7CLJP5USTMDT5LRZFANCNFSM5CKZWSGQ&data=04%7C01%7Cmort963%40temple.edu%7C818734b7e125421ec56208d961d1a132%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637648375258379169%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XU20iGFDcFTRyqjPFapPGR8iERm6t%2FKmpjrj57i3WNI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmort963%40temple.edu%7C818734b7e125421ec56208d961d1a132%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637648375258389164%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=L%2FUYRP%2F2Icd01%2BJf0kgEDHDzlj1Z9WVP93GQ0aoe2Zc%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cmort963%40temple.edu%7C818734b7e125421ec56208d961d1a132%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637648375258389164%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8sZGTXrFs38b%2BDOcQBLqFS590BXDME2JuB%2Btle6Sjfk%3D&reserved=0>.

**Comment by bwiernik** [comment]
Can you please run this and post the results:

`devtools::session_info()`

**Comment by IndrajeetPatil** [comment]
`Error in grid.Call` actually has to do with RStudio, and not `{performance}`.

This can possibly be solved by increasing the size of RStudio viewer pane.

**Comment by dpmoriarity** [comment]
....welp. Did not know that was a potential source of errors. Thank you for your help!

My best,
Daniel

Doctoral Student, Clinical Area
Mood and Cognition Lab
Department of Psychology
Temple University

________________________________
From: Indrajeet Patil ***@***.***>
Sent: Wednesday, August 18, 2021 2:43 AM
To: easystats/performance ***@***.***>
Cc: Daniel P Moriarity ***@***.***>; Author ***@***.***>
Subject: [External] Re: [easystats/performance] check_model(x) Error in grid.Call.... (#353)


Error in grid.Call actually has to do with RStudio, and not {performance}.

This can possibly be solved by increasing the size of RStudio viewer pane.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Feasystats%2Fperformance%2Fissues%2F353%23issuecomment-900861685&data=04%7C01%7Cmort963%40temple.edu%7C558be5a0c78745845d5608d962138b63%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637648658373108391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JG6paEumqYD5%2B%2Ben8NKLVj3AmuHkCeYWJ5i%2FS3NuvMg%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJ52725QAGRVBV4PRJEEOKDT5NJCTANCNFSM5CKZWSGQ&data=04%7C01%7Cmort963%40temple.edu%7C558be5a0c78745845d5608d962138b63%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637648658373108391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sXewHCE7JzAUbykuOevCa9ykktSOY2aa9KfeLnppdwQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmort963%40temple.edu%7C558be5a0c78745845d5608d962138b63%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637648658373118379%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cq7i3ucNtvVjwq8LLrq0tEotdzOfEvMyzQkBP3DRGgI%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cmort963%40temple.edu%7C558be5a0c78745845d5608d962138b63%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637648658373118379%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=32xTlbjjpxOENYhPDHYU0gUQO%2B4hCRovm%2BWHV9x0JBo%3D&reserved=0>.

**Comment by brshallo** [comment]
I had this same issue too. Updating `{see}` did not fix it. Though per IndrajeetPatil comment, expanding the size of the Rstudio viewer did. Also setting `panel = FALSE`, outputs works fine. I also only had problems in interactive session. Running a Reprex worked fine, e.g.:

``` r
library(performance)

m <- lm(mpg ~ wt + cyl, data = mtcars)
check_model(m)
```

![](https://i.imgur.com/JmQg1er.png)

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/Los_Angeles         
#>  date     2021-10-20                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version    date       lib
#>  assertthat    0.2.1      2019-03-21 [1]
#>  backports     1.2.1      2020-12-09 [1]
#>  bayestestR    0.11.5     2021-10-21 [1]
#>  cachem        1.0.5      2021-05-15 [1]
#>  callr         3.7.0      2021-04-20 [1]
#>  cli           3.0.1      2021-07-17 [1]
#>  colorspace    2.0-1      2021-05-04 [1]
#>  crayon        1.4.1      2021-02-08 [1]
#>  datawizard    0.2.1.9000 2021-10-21 [1]
#>  DBI           1.1.1      2021-01-15 [1]
#>  DEoptimR      1.0-8      2016-11-19 [1]
#>  desc          1.3.0      2021-03-05 [1]
#>  devtools      2.4.1      2021-05-05 [1]
#>  digest        0.6.27     2020-10-24 [1]
#>  dplyr         1.0.7      2021-06-18 [1]
#>  ellipsis      0.3.2      2021-04-29 [1]
#>  evaluate      0.14       2019-05-28 [1]
#>  fansi         0.5.0      2021-05-25 [1]
#>  farver        2.1.0      2021-02-28 [1]
#>  fastmap       1.1.0      2021-01-25 [1]
#>  fs            1.5.0      2020-07-31 [1]
#>  generics      0.1.0      2020-10-31 [1]
#>  ggplot2       3.3.5      2021-06-25 [1]
#>  ggrepel       0.9.1      2021-01-15 [1]
#>  glue          1.4.2      2020-08-27 [1]
#>  gtable        0.3.0      2019-03-25 [1]
#>  highr         0.9        2021-04-16 [1]
#>  htmltools     0.5.1.1    2021-01-22 [1]
#>  insight       0.14.5.1   2021-10-21 [1]
#>  knitr         1.33       2021-04-24 [1]
#>  labeling      0.4.2      2020-10-20 [1]
#>  lattice       0.20-35    2017-03-25 [2]
#>  lifecycle     1.0.0      2021-02-15 [1]
#>  magrittr      2.0.1      2020-11-17 [1]
#>  MASS          7.3-50     2018-04-30 [2]
#>  Matrix        1.2-14     2018-04-13 [1]
#>  memoise       2.0.0      2021-01-26 [1]
#>  mgcv          1.8-24     2018-06-23 [2]
#>  munsell       0.5.0      2018-06-12 [1]
#>  nlme          3.1-137    2018-04-07 [2]
#>  patchwork     1.1.1      2020-12-17 [1]
#>  performance * 0.8.0.1    2021-10-21 [1]
#>  pillar        1.6.2      2021-07-29 [1]
#>  pkgbuild      1.2.0      2020-12-15 [1]
#>  pkgconfig     2.0.3      2019-09-22 [1]
#>  pkgload       1.2.1      2021-04-06 [1]
#>  prettyunits   1.1.1      2020-01-24 [1]
#>  processx      3.5.2      2021-04-30 [1]
#>  ps            1.6.0      2021-02-28 [1]
#>  purrr         0.3.4      2020-04-17 [1]
#>  qqplotr       0.0.5      2021-04-23 [1]
#>  R6            2.5.0      2020-10-28 [1]
#>  Rcpp          1.0.7      2021-07-07 [1]
#>  remotes       2.3.0      2021-04-01 [1]
#>  reprex        2.0.0      2021-04-02 [1]
#>  rlang         0.4.11     2021-04-30 [1]
#>  rmarkdown     2.10       2021-08-06 [1]
#>  robustbase    0.93-7     2021-01-04 [1]
#>  rprojroot     2.0.2      2020-11-15 [1]
#>  rstudioapi    0.13       2020-11-12 [1]
#>  scales        1.1.1      2020-05-11 [1]
#>  see           0.6.8      2021-10-03 [1]
#>  sessioninfo   1.1.1      2018-11-05 [1]
#>  stringi       1.7.3      2021-07-16 [1]
#>  stringr       1.4.0      2019-02-10 [1]
#>  styler        1.4.0      2021-03-22 [1]
#>  testthat      3.0.2      2021-02-14 [1]
#>  tibble        3.1.3      2021-07-23 [1]
#>  tidyselect    1.1.1      2021-04-30 [1]
#>  usethis       2.0.1      2021-02-10 [1]
#>  utf8          1.2.2      2021-07-24 [1]
#>  vctrs         0.3.8      2021-04-29 [1]
#>  withr         2.4.2      2021-04-18 [1]
#>  xfun          0.25       2021-08-06 [1]
#>  yaml          2.2.1      2020-02-01 [1]
#>  source                                    
#>  CRAN (R 3.5.3)                            
#>  CRAN (R 3.5.1)                            
#>  https://easystats.r-universe.dev (R 3.5.1)
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  https://easystats.r-universe.dev (R 3.5.1)
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.0)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.3)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.3)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  https://easystats.r-universe.dev (R 3.5.1)
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  https://easystats.r-universe.dev (R 3.5.1)
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.3)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.3)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.3)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.2)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.3)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.1)                            
#>  CRAN (R 3.5.3)                            
#> 
#> [1] C:/Users/BSHALLOW/Documents/R/win-library/3.5
#> [2] C:/Program Files/R/R-3.5.1/library
```

<sup>Created on 2021-10-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
